apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devoteam-demo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/lopes221/argoCD.git
    targetRevision: HEAD
    path: nginx/
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
